<?php

return [
    'dashboard' => 'dashboard',
    'items' => 'all-items',
    'import-items' => 'import-items',
    'labels' => 'labels',
    'add-item' => 'add-item',
    'edit-item' => 'edit-item',
    'view-item' => 'view-item',
    'categories' => 'all-categories',
    'add-cat' => 'add-category',
    'edit-cat' => 'edit-category',
    'manufacturers' => 'all-manufacturers',
    'add-manufacturer' => 'add-manufacturer',
    'edit-manufacturer' => 'edit-manufacturer',
    // Manufacturers were called brands until they were renamed; the old
    // addresses still work so saved links do not break.
    'brands' => 'all-manufacturers',
    'add-brand' => 'add-manufacturer',
    'edit-brand' => 'edit-manufacturer',
    'suppliers' => 'all-suppliers',
    'add-supplier' => 'add-supplier',
    'edit-supplier' => 'edit-supplier',
    'locations' => 'all-locations',
    'add-loc' => 'add-location',
    'edit-loc' => 'edit-location',
    'statuses' => 'all-statuses',
    'add-status' => 'add-status',
    'edit-status' => 'edit-status',
    'add-deployment' => 'add-deployment',
    'edit-deployment' => 'edit-deployment',
    'export-items' => 'export-items',
    'projects' => 'all-projects',
    'add-project' => 'add-project',
    'edit-project' => 'edit-project',
    'view-project' => 'view-project',
    'shopping-list' => 'shopping-list',
    'add-assembly' => 'add-assembly',
    'edit-assembly' => 'edit-assembly',
    'view-assembly' => 'view-assembly',
    'add-assembly-item' => 'add-assembly-item',
    'edit-assembly-item' => 'edit-assembly-item',
];